server:
  port: 8003
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: Saurabh@15

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


    
